stages:
- build-package-npm
- test-package-npm

build-package-npm 1/2:
  stage: build-package-npm
  before_script: echo npm install
  script:
  - echo npm run build
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

build-package-npm 2/2:
  stage: build-package-npm
  script:
  - echo npm clean
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-npm 1/2:
  stage: test-package-npm
  script:
  - echo npm run test
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-npm 2/2:
  stage: test-package-npm
  before_script:
  - echo npm install
  - echo npm install eslint
  script:
  - echo node_modules/eslint/bin/eslint.js .
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행
