stages:
- build-package-npm
- test-package-npm

build-package-npm 1/2:
  stage: build-package-npm
  before_script: npm install
  script:
  - npm run build
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-npm 1/2:
  stage: test-package-npm
  script:
  - npm run test
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-npm 2/2:
  stage: test-package-npm
  script:
  - npm run lint
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행
