.pipeline-target
  only:
  - main
  - dev
  - merge_reqeusts
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행
    changes:
    - "front-end/**/*"

stages:
- build-package-npm
- test-package-npm

build-package-npm 1/2:
  stage: build-package-npm
  extends: .pipeline-target
  befroe_script: echo npm install
  script:
  - echo npm run build

build-package-npm 2/2:
  stage: build-package-npm
  extends: .pipeline-target
  script:
  - echo npm clean

test-package-npm 1/2:
  stage: test-package-npm
  extends: .pipeline-target
  script:
  - echo npm run test
test-package-npm 2/2:
  stage: test-package-npm
  extends: .pipeline-target
  before_script:
  - echo npm install
  - echo npm install eslint
  script:
  - echo node_modules/eslint/bin/eslint.js .
