image: gradle:latest

stages:
- build-package-gradle
- test-package-gradle

build-package-gradle 1/1:
  stage: build-package-gradle
  before_script:
  - cd back-end
  - chmod 777 ./gradlew
  script:
  - ./gradlew build
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-gradle 1/2:
  stage: test-package-gradle
  before_script:
  - cd back-end
  - chmod 777 ./gradlew
  script:
  - ./gradlew test
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행

test-package-gradle 1/2:
  stage: test-package-gradle
  before_script:
  - cd back-end
  - chmod 777 ./gradlew
  script:
  - ./gradlew check
  only:
  - main
  - dev
  - merge_requests
  - /^feat\/.*$/   # 특정 브랜치 패턴에서 실행



